apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "aws-cloudwatch-metrics.fullname" . }}
  labels:
    {{- include "aws-cloudwatch-metrics.labels" . | nindent 4 }}
data:
  cwagentconfig.json: |
    {
      {{- if .Values.region }}
      "agent": {
        "region": "{{ .Values.region }}"
      },
      {{- end }}
      "logs": {
        "metrics_collected": {
          "kubernetes": {
            "cluster_name": "{{ .Values.clusterName }}",
            "metrics_collection_interval": 60
          }
        },
        "force_flush_interval": 5
      }
    }